export const widgetMap = {
  STATUS_BAR_WIDGET: 'STATUS_BAR_WIDGET',
  HEADER_MESSAGES_WIDGET: 'HEADER_MESSAGES_WIDGET',
  HEADER_CHAT_WIDGET: 'HEADER_CHAT_WIDGET',
  TAB_BAR_WIDGET: 'TAB_BAR_WIDGET',
  FAVORITE_LIST_WIDGET: 'FAVORITE_LIST_WIDGET',
  MESSAGES_LIST_WIDGET: 'MESSAGES_LIST_WIDGET',
  CHAT_LIST_WIDGET: 'CHAT_LIST_WIDGET',
  CHAT_INPUT_WIDGET: 'CHAT_INPUT_WIDGET',
  SEPARATOR_WIDGET: 'SEPARATOR_WIDGET',
};
